### ISSUE TITLE
scalajs support

### ISSUE THREAD

**Issue by antonkulaga** [JuPfu/chelona#3]
It would be nice to crosscompile it to scala/scalajs

**Comment by JuPfu** [comment]
Hi, I will go for it. First, step will be to set an appropriate baseline as I did some experiments with parallelization, which might lead to problems in case of syntactic errors encountered in input data.
Next step is to cross compile to scala/scalajs.
Kind regards, Jürgen

**Comment by antonkulaga** [comment]
I made a PR #4 to add scalajs support. Tests on scalajs part fail but it is because of parallelization that is not fully supported in scalajs. I do not have time now to deal  with it

**Comment by JuPfu** [comment]
I am considering to create a branch in which  the parallelization parts will be removed, at least temporarily. This branch should be used for cross-compiling to scalajs.

**Comment by JuPfu** [comment]
Merged your changes in branch scalajs.
Next step is to have a look at the parallelization to make all tests pass.
As I am not a Git-professional, my proceedings might not match the standards. 
If you like to have write access to the project, I gladly will assign them to you.
Kind regards,
Jürgen

**Comment by antonkulaga** [comment]
I am ok with just sending PRs. Unfortunately, I have very little free time - not enough to delete parallelization that does not work in scalajs For me editing parboiled rules takes a lot of time because (unlike with FastParse) Intellij IDEA error highlighting is totally wrong with parboiled2, so I have to work almost blindly with it.

**Comment by antonkulaga** [comment]
any progress on separating async stuff from the parser?

**Comment by JuPfu** [comment]
Hi Anton,
yes, I removed the multi-threading from the parser and compiled it successfully.
I could run some tests manually (see chelona/js/src/main/scala/org/chelona/MainJS.scala
 on the scalajs branch).

At the moment I am looking for a way to modify the test modules (see chelona/jvm/src/test/scala/org/chelona/) to get them compiled and run with scalajs. Each test case reads the test data from file. Any suggestions how to do adapt it for scalajs (besides to embed each file data in the test module and to use a StringReader) ?

Is there a best practise how to publish the scala-js version of a project ? Any hints, links, support is welcome!

Kind regards
Jürgen

**Comment by JuPfu** [comment]
Preparing for publishing scala-js version.
Any comments, remarks or known problems ?

**Comment by JuPfu** [comment]
@antonkulaga 
May I add you as developer to the project as you started the scalajs support ?

**Comment by JuPfu** [comment]
@antonkulaga 
chelona_sjs0.6_2.11-1.2.0.jar published  on Sonatype.

Update of documentation is in progress. I will open a separate issue for it.

**Comment by antonkulaga** [comment]
Great news, @JuPfu , I will try to integrate it to banana-rdf. Sorry for being not responsive - I was in the conference last week.
